version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.1
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
  - dependency-name: clean-css
    versions:
    - 4.2.3
    - 5.0.1
    - 5.1.0
    - 5.1.1
  - dependency-name: jquery
    versions:
    - 3.5.1
